from __future__ import annotations

from typing import Any

CATALOG: dict[str, dict[str, Any]] = {
    "payment-latency": {
        "title": "Payment latency after deployment",
        "source": "prometheus",
        "name": "PaymentLatencyHigh",
        "service": "payments",
        "severity": "CRITICAL",
        "description": "p95 latency above 1200ms for payments checkout path after Deployment 2.5",
        "labels": {"cluster": "prod-us-east-1", "deployment": "payments-api", "team": "payments-sre"},
        "annotations": {"summary": "Payment latency regression"},
    },
    "checkout-pod-crash": {
        "title": "Checkout pod crash loop",
        "source": "kubernetes",
        "name": "CheckoutPodCrashLoop",
        "service": "checkout",
        "severity": "HIGH",
        "description": "checkout-api pods are crash looping after config reload",
        "labels": {"cluster": "prod-us-east-1", "deployment": "checkout-api", "team": "checkout-sre"},
        "annotations": {"summary": "Checkout pods restarting"},
    },
    "inventory-cpu": {
        "title": "Inventory CPU saturation",
        "source": "datadog",
        "name": "InventoryCpuSaturation",
        "service": "inventory",
        "severity": "HIGH",
        "description": "inventory service CPU above 92 percent during catalog sync",
        "labels": {"cluster": "prod-us-east-1", "deployment": "inventory-api", "team": "commerce-sre"},
        "annotations": {"summary": "Inventory CPU saturation"},
    },
    "redis-cache": {
        "title": "Redis cache saturation",
        "source": "grafana",
        "name": "RedisCacheSaturation",
        "service": "cache",
        "severity": "WARNING",
        "description": "redis cache memory pressure causing elevated misses",
        "labels": {"cluster": "prod-us-east-1", "deployment": "redis-cache", "team": "platform-sre"},
        "annotations": {"summary": "Cache memory pressure"},
    },
    "database-replica-lag": {
        "title": "Database replica lag",
        "source": "azure monitor",
        "name": "DatabaseReplicaLag",
        "service": "orders-db",
        "severity": "CRITICAL",
        "description": "orders database replica lag above 180 seconds",
        "labels": {"cluster": "prod-us-east-1", "deployment": "orders-postgres", "team": "database-sre"},
        "annotations": {"summary": "Replica lag impacting reads"},
    },
    "auth-errors": {
        "title": "Authentication error spike",
        "source": "splunk",
        "name": "AuthErrorRateHigh",
        "service": "auth",
        "severity": "HIGH",
        "description": "auth 5xx errors increased after secret rotation",
        "labels": {"cluster": "prod-us-east-1", "deployment": "auth-api", "team": "identity-sre"},
        "annotations": {"summary": "Auth failures after rotation"},
    },
    "search-memory": {
        "title": "Search memory leak",
        "source": "prometheus",
        "name": "SearchMemoryHigh",
        "service": "search",
        "severity": "HIGH",
        "description": "search service memory increasing steadily after index refresh",
        "labels": {"cluster": "prod-us-east-1", "deployment": "search-api", "team": "search-sre"},
        "annotations": {"summary": "Memory leak suspected"},
    },
    "billing-terraform": {
        "title": "Billing infrastructure regression",
        "source": "terraform",
        "name": "BillingInfraRegression",
        "service": "billing",
        "severity": "CRITICAL",
        "description": "billing private endpoint unreachable after terraform apply",
        "labels": {"cluster": "prod-us-east-1", "deployment": "billing-network", "team": "finops-sre"},
        "annotations": {"summary": "Terraform network regression"},
    },
    "fraud-api": {
        "title": "Fraud API dependency timeout",
        "source": "datadog",
        "name": "FraudApiTimeouts",
        "service": "fraud",
        "severity": "HIGH",
        "description": "fraud scoring API timeout rate above threshold",
        "labels": {"cluster": "prod-us-east-1", "deployment": "fraud-api", "team": "risk-sre"},
        "annotations": {"summary": "Fraud scoring timeouts"},
    },
    "cdn-errors": {
        "title": "CDN error rate increase",
        "source": "grafana",
        "name": "CdnErrorRateHigh",
        "service": "cdn",
        "severity": "WARNING",
        "description": "cdn 5xx error rate elevated in edge region",
        "labels": {"cluster": "global-edge", "deployment": "cdn-rules", "team": "edge-sre"},
        "annotations": {"summary": "Edge errors elevated"},
    },
}

# Backwards-compatible alias for callers that imported SCENARIOS previously.
SCENARIOS = CATALOG
