from __future__ import annotations

from typing import Any

SCENARIOS: dict[str, dict[str, Any]] = {
    "payment-latency": {
        "title": "Payment latency after deployment",
        "source": "prometheus",
        "name": "PaymentLatencyHigh",
        "service": "payments",
        "severity": "CRITICAL",
        "description": "p95 latency above 1200ms for payments checkout path after Deployment 2.5",
        "labels": {"cluster": "prod-us-east-1", "deployment": "payments-api", "team": "payments-sre"},
        "annotations": {"summary": "Payment latency regression"},
        "root_cause": "Deployment 2.5",
        "impact": "Payment latency",
        "recommended_action": "Rollback deployment",
        "remediation_comment": "Rollback deployment",
        "action_type": "rollback",
        "target": "payments-api",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/payments-rollback-v3.md",
        "related_incidents": ["INC-8842", "INC-7211"],
        "dependency_services": ["checkout", "fraud", "orders-db"],
        "recent_changes": ["CHG-90211 Deployment 2.5", "CHG-90123 Feature flag enable"],
    },
    "checkout-pod-crash": {
        "title": "Checkout pod crash loop",
        "source": "kubernetes",
        "name": "CheckoutPodCrashLoop",
        "service": "checkout",
        "severity": "HIGH",
        "description": "checkout-api pods are crash looping after config reload",
        "labels": {"cluster": "prod-us-east-1", "deployment": "checkout-api", "team": "checkout-sre"},
        "annotations": {"summary": "Checkout pods restarting"},
        "root_cause": "Bad runtime config reload",
        "impact": "Checkout availability degradation",
        "recommended_action": "Restart pod",
        "remediation_comment": "Restart pod",
        "action_type": "restart",
        "target": "checkout-api",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/checkout-pod-restart.md",
        "related_incidents": ["INC-7732"],
        "dependency_services": ["payments", "cart", "inventory"],
        "recent_changes": ["CHG-90212 Config reload"],
    },
    "inventory-cpu": {
        "title": "Inventory CPU saturation",
        "source": "datadog",
        "name": "InventoryCpuSaturation",
        "service": "inventory",
        "severity": "HIGH",
        "description": "inventory service CPU above 92 percent during catalog sync",
        "labels": {"cluster": "prod-us-east-1", "deployment": "inventory-api", "team": "commerce-sre"},
        "annotations": {"summary": "Inventory CPU saturation"},
        "root_cause": "Catalog sync traffic spike",
        "impact": "Inventory lookup latency",
        "recommended_action": "Scale deployment",
        "remediation_comment": "Scale deployment",
        "action_type": "scale",
        "target": "inventory-api",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/inventory-scale.md",
        "related_incidents": ["INC-7411"],
        "dependency_services": ["catalog", "search", "orders"],
        "recent_changes": ["CHG-90155 Catalog sync schedule"],
    },
    "redis-cache": {
        "title": "Redis cache saturation",
        "source": "grafana",
        "name": "RedisCacheSaturation",
        "service": "cache",
        "severity": "WARNING",
        "description": "redis cache memory pressure causing elevated misses",
        "labels": {"cluster": "prod-us-east-1", "deployment": "redis-cache", "team": "platform-sre"},
        "annotations": {"summary": "Cache memory pressure"},
        "root_cause": "Hot keys and stale cache entries",
        "impact": "API latency from cache misses",
        "recommended_action": "Clear cache",
        "remediation_comment": "Clear cache",
        "action_type": "cache_evict",
        "target": "redis-cache",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/redis-eviction.md",
        "related_incidents": ["INC-6601"],
        "dependency_services": ["catalog", "payments", "search"],
        "recent_changes": ["CHG-90090 Cache TTL increase"],
    },
    "database-replica-lag": {
        "title": "Database replica lag",
        "source": "azure monitor",
        "name": "DatabaseReplicaLag",
        "service": "orders-db",
        "severity": "CRITICAL",
        "description": "orders database replica lag above 180 seconds",
        "labels": {"cluster": "prod-us-east-1", "deployment": "orders-postgres", "team": "database-sre"},
        "annotations": {"summary": "Replica lag impacting reads"},
        "root_cause": "Primary database write saturation",
        "impact": "Stale order reads",
        "recommended_action": "Failover database",
        "remediation_comment": "Failover database",
        "action_type": "db_failover",
        "target": "orders-postgres",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/orders-db-failover.md",
        "related_incidents": ["INC-9011", "INC-8821"],
        "dependency_services": ["orders", "fulfillment", "reporting"],
        "recent_changes": ["CHG-90299 Write-heavy campaign"],
    },
    "auth-errors": {
        "title": "Authentication error spike",
        "source": "splunk",
        "name": "AuthErrorRateHigh",
        "service": "auth",
        "severity": "HIGH",
        "description": "auth 5xx errors increased after secret rotation",
        "labels": {"cluster": "prod-us-east-1", "deployment": "auth-api", "team": "identity-sre"},
        "annotations": {"summary": "Auth failures after rotation"},
        "root_cause": "Secret rotation mismatch",
        "impact": "Login failures",
        "recommended_action": "Restart service",
        "remediation_comment": "Restart service",
        "action_type": "restart",
        "target": "auth-api",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/auth-secret-rollback.md",
        "related_incidents": ["INC-6711"],
        "dependency_services": ["session", "api-gateway", "users"],
        "recent_changes": ["CHG-90301 Secret rotation"],
    },
    "search-memory": {
        "title": "Search memory leak",
        "source": "prometheus",
        "name": "SearchMemoryHigh",
        "service": "search",
        "severity": "HIGH",
        "description": "search service memory increasing steadily after index refresh",
        "labels": {"cluster": "prod-us-east-1", "deployment": "search-api", "team": "search-sre"},
        "annotations": {"summary": "Memory leak suspected"},
        "root_cause": "Index refresh memory leak",
        "impact": "Search latency and OOM risk",
        "recommended_action": "Restart service",
        "remediation_comment": "Restart service",
        "action_type": "restart",
        "target": "search-api",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/search-restart.md",
        "related_incidents": ["INC-7022"],
        "dependency_services": ["catalog", "inventory"],
        "recent_changes": ["CHG-90212 Index refresh job"],
    },
    "billing-terraform": {
        "title": "Billing infrastructure regression",
        "source": "terraform",
        "name": "BillingInfraRegression",
        "service": "billing",
        "severity": "CRITICAL",
        "description": "billing private endpoint unreachable after terraform apply",
        "labels": {"cluster": "prod-us-east-1", "deployment": "billing-network", "team": "finops-sre"},
        "annotations": {"summary": "Terraform network regression"},
        "root_cause": "Terraform security group change",
        "impact": "Billing job failures",
        "recommended_action": "Terraform rollback",
        "remediation_comment": "Terraform rollback",
        "action_type": "terraform_rollback",
        "target": "billing-network",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/terraform-rollback.md",
        "related_incidents": ["INC-9311"],
        "dependency_services": ["payments", "reporting"],
        "recent_changes": ["CHG-90412 Terraform apply"],
    },
    "fraud-api": {
        "title": "Fraud API dependency timeout",
        "source": "datadog",
        "name": "FraudApiTimeouts",
        "service": "fraud",
        "severity": "HIGH",
        "description": "fraud scoring API timeout rate above threshold",
        "labels": {"cluster": "prod-us-east-1", "deployment": "fraud-api", "team": "risk-sre"},
        "annotations": {"summary": "Fraud scoring timeouts"},
        "root_cause": "Dependency pool exhaustion",
        "impact": "Checkout risk checks delayed",
        "recommended_action": "API execution",
        "remediation_comment": "API execution",
        "action_type": "api_execution",
        "target": "fraud-api",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/fraud-pool-resize.md",
        "related_incidents": ["INC-7510"],
        "dependency_services": ["payments", "checkout"],
        "recent_changes": ["CHG-90212 Pool size change"],
    },
    "cdn-errors": {
        "title": "CDN error rate increase",
        "source": "grafana",
        "name": "CdnErrorRateHigh",
        "service": "cdn",
        "severity": "WARNING",
        "description": "cdn 5xx error rate elevated in edge region",
        "labels": {"cluster": "global-edge", "deployment": "cdn-rules", "team": "edge-sre"},
        "annotations": {"summary": "Edge errors elevated"},
        "root_cause": "Bad edge rule propagation",
        "impact": "Static asset failures",
        "recommended_action": "API execution",
        "remediation_comment": "API execution",
        "action_type": "api_execution",
        "target": "cdn-rules",
        "downstream_agents": ["context-agent", "resolution-agent", "remediation-engine"],
        "runbook": "runbooks/cdn-rule-rollback.md",
        "related_incidents": ["INC-5512"],
        "dependency_services": ["frontend", "media"],
        "recent_changes": ["CHG-90511 Edge rule push"],
    },
}
