apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kaiops-api-hpa
  namespace: kaiops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kaiops-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
