apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kaiops-ingress
  namespace: kaiops
spec:
  rules:
    - host: kaiops.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kaiops-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kaiops-web
                port:
                  number: 80
